name: "Homebridge Test-Instanz"
version: "2.1.6"
slug: "homebridge_test"
description: "Zweite Homebridge Instanz auf Port 8582"
url: "https://github.com/GodOfGodless/hassio-addons"
arch:
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8582/tcp: 8582
ports_description:
  8582/tcp: "Homebridge Test-UI"
webui: "http://[HOST]:[PORT:8582]"
host_network: true
init: false
map:
  - homeassistant_config:rw
options: {}
schema: {}
